// Controlled browser-device branches. No real microphone, network or speaker.
const {test,afterEach}=require('node:test');
const assert=require('node:assert/strict');
const Voice=require('../static/voice.js');
const instances=[];
global.window={};
global.crypto=require('node:crypto').webcrypto;
global.localStorage={data:new Map(),getItem(k){return this.data.get(k)||null;},setItem(k,v){this.data.set(k,v);},removeItem(k){this.data.delete(k);}};
global.fetch=async()=>({ok:true});
function make(api=async()=>{}){let ctx={childId:'synthetic',conversationId:'conv',maxSeconds:60};const texts=[];const v=new Voice({api,context:()=>ctx,changed(){},transcript(...args){texts.push(args);},notice(){}});instances.push(v);return {v,texts,change:()=>ctx={...ctx,childId:'another'}};}
function media(getUserMedia){Object.defineProperty(global,'navigator',{configurable:true,value:{mediaDevices:{getUserMedia}}});window.MediaRecorder=global.MediaRecorder=class {static isTypeSupported(){return true;}constructor(stream){this.state='inactive';this.mimeType='audio/webm';}start(){this.state='recording';}stop(){if(this.state==='inactive')throw Error('double stop');this.state='inactive';this.onstop?.();}};}
afterEach(()=>{instances.splice(0).forEach(v=>v.stop());localStorage.data.clear();});
test('microphone only opens after record; denied permission is recoverable',async()=>{let opened=0;media(async()=>{opened++;throw Object.assign(Error(),{name:'NotAllowedError'});});const {v}=make();assert.equal(opened,0);await v.record();assert.equal(opened,1);assert.equal(v.phase,'asr_error');assert.match(v.error,/权限/);});
test('cancelling permission or changing profile releases a late stream',async()=>{let resolve,stopped=0;media(()=>new Promise(r=>resolve=r));const {v,change}=make();const pending=v.record();change();v.stop();resolve({getTracks:()=>[{stop(){stopped++;}}]});await pending;assert.equal(stopped,1);assert.equal(v.phase,'idle');});
test('repeated end-click uploads once and releases recorder tracks',async()=>{let stopped=0,converted=0;media(async()=>({getTracks:()=>[{stop(){stopped++;}}]}));const {v}=make();v.convertAndRecognize=async()=>{converted++;v.update('recognizing');};await v.record();await v.record();await v.record();assert.equal(converted,1);assert.equal(stopped,1);assert.equal(v.phase,'recognizing');});
test('stopping recording never launches ASR from late onstop',async()=>{let converted=0,stopped=0;media(async()=>({getTracks:()=>[{stop(){stopped++;}}]}));const {v}=make();v.convertAndRecognize=async()=>{converted++;};await v.record();v.stop();assert.equal(converted,0);assert.ok(stopped>=1);assert.equal(v.stream,null);assert.equal(v.recorder,null);});
test('blocked playback remains ready; replay reuses audio without API',async()=>{let plays=0,calls=0;const {v}=make(async()=>{calls++;});v.messageId='saved';v.audio={play:async()=>{plays++;throw Object.assign(Error(),{name:'NotAllowedError'});},pause(){},removeAttribute(){},load(){}};await v.playAudio(v.epoch,v.context());assert.equal(v.phase,'play_ready');assert.match(v.error,/再点一次/);await v.speak('saved');assert.equal(calls,0);assert.equal(plays,2);});
test('playing starts only with actual playing event; navigation releases audio',async()=>{let lastAudio;global.Audio=class {constructor(){lastAudio=this;this.paused=false;}async play(){}pause(){this.paused=true;}removeAttribute(){this.cleared=true;}load(){}};const {v}=make();v.messageId='saved';await v.poll({id:'cached',kind:'tts',status:'completed'},v.epoch,v.context());assert.equal(v.phase,'play_ready');lastAudio.onplaying();assert.equal(v.phase,'playing');v.stop();assert.ok(lastAudio.paused&&lastAudio.cleared);lastAudio.onplaying();assert.equal(v.phase,'idle');});
test('ASR recovery delivers editable text once and never generates chat',async()=>{let calls=[];const {v,texts}=make(async path=>{calls.push(path);return {id:'saved',kind:'asr',status:'completed',text:'合成问题',inputKind:'audio_file'};});localStorage.setItem(v.taskKey(),JSON.stringify({id:'saved',kind:'asr'}));await v.recover();assert.equal(texts.length,1);assert.equal(localStorage.getItem(v.taskKey()),null);assert.ok(calls.every(p=>p.startsWith('/api/speech/request?')));});
test('PCM encoding writes actual mono 16 kHz WAV sizes',()=>{const bytes=Voice.encodeWav(new Float32Array([0,1,-1]));const view=new DataView(bytes.buffer);assert.equal(view.getUint32(24,true),16000);assert.equal(view.getUint16(22,true),1);assert.equal(view.getUint32(40,true),6);assert.equal(view.getInt16(46,true),32767);assert.equal(view.getInt16(48,true),-32768);});
test('known invalid audio is not presented as an unknown paid request',async()=>{const {v}=make(async()=>{throw Object.assign(Error('这段音频没有声音'),{status:400,code:'audio_empty'});});v.raw=new Uint8Array([1,2]);await v.recognize();assert.equal(v.phase,'asr_error');assert.equal(v.unknown,false);assert.equal(v.raw,null);assert.equal(v.job,null);assert.equal(localStorage.getItem(v.taskKey()),null);});
test('network uncertainty recovers the original ASR request before retrying',async()=>{const {v}=make(async()=>{throw Error('连接中断');});v.raw=new Uint8Array([1,2]);await v.recognize();assert.equal(v.phase,'asr_error');assert.equal(v.unknown,true);assert.equal(v.job.status,'pending');assert.ok(localStorage.getItem(v.taskKey()));});
